runtime: python39  # or the version you are using

entrypoint: gunicorn -b :$PORT main:app  # replace 'main' with the name of your Flask app file without the '.py'

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
